spring:
  profiles:
    group:
      local:
        - global
        - local
      dev:
        - global
        - dev
      prd:
        - global
        - prd
      test:
        - global
        - test